version: '3.8'

services:
  php-container:
    container_name: php-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./apache/000-apache.conf:/etc/apache2/sites-available/000-default.conf
    restart: always